
                                                                                                                                                                                                                                                                                                                                                                                            import 'package:flutter/material.dart';

                                                                                                                                                                                                                                                                                                                                                                                            void main() => runApp(const MyApp());

                                                                                                                                                                                                                                                                                                                                                                                            class MyApp extends StatelessWidget {
                                                                                                                                                                                                                                                                                                                                                                                              const MyApp({super.key});
                                                                                                                                                                                                                                                                                                                                                                                                @override
                                                                                                                                                                                                                                                                                                                                                                                                  Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                      return MaterialApp(
                                                                                                                                                                                                                                                                                                                                                                                                            title: '   ',
                                                                                                                                                                                                                                                                                                                                                                                                                  theme: ThemeData.dark().copyWith(
                                                                                                                                                                                                                                                                                                                                                                                                                          colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                      home: const HomePage(),
                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                            class HomePage extends StatelessWidget {
                                                                                                                                                                                                                                                                                                                                                                                                                                              const HomePage({super.key});
                                                                                                                                                                                                                                                                                                                                                                                                                                                @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                  Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            appBar: AppBar(title: const Text('AI Magic App')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  body: Center(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: const EdgeInsets.all(24.0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Icon(Icons.auto_awesome, size: 64, color: Colors.cyanAccent),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'أصنع لي تطبيق اذكار',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style: TextStyle(fontSize: 22, fontWeight: FontWeight.w300),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            SizedBox(height: 40),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ElevatedButton.icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onPressed: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          icon: Icon(Icons.star),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          label: Text('Get Started'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }